name: dotnet package

on: [push]

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0
      - name: Restore
        run: dotnet restore ExtractAll/ExtractAll.csproj
      - name: Publish
        run: dotnet publish ExtractAll/ExtractAll.csproj
      - name: Make Dir
        run: mkdir ./win-certs
      - name: Make Dir
        run: cd ./win-certs
      - name: Extract Certs
        run: ../ExtractAll/bin/Release/net8.0/ExtractAll.exe
      - name: Move up
        run: cd ..
      - uses: actions/upload-artifact@v4
        with:
          name: win-certs
          path: ./win-certs
  
  build-docker:
    runs-on: ubuntu-latest
    needs: build-win
    steps:
    - name: Set output
      id: vars
      run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

    - name: Check output
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - uses: actions/download-artifact@v4
      with:
        name: win-certs
        path: ./data

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ vars.DOCKERHUB_USERNAME }}/root-certificates
      
    - name: Build and push Docker image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        push: true
        tags: ${{ vars.DOCKERHUB_USERNAME }}/root-certificates:${{ steps.vars.outputs.tag }} , ${{ vars.DOCKERHUB_USERNAME }}/root-certificates:latest